services:
  # Serviço Giro
  giro:
    build:
      context: ./giro
    container_name: giro
    ports:
      - "9999:9999"
    volumes:
      - ./giro/internal/stubs:/app/internal/stubs
      - ./giro/test.db:/app/test.db
    networks:
      - passcom
    command: ["./app"]

  giro_ui:
    build:
      context: ./giro/ui
    ports:
      - "5173:5173"
    networks:
      - passcom
    depends_on:
      - giro

  # Serviço Rumos
  # rumos:
  #   build:
  #     context: ./rumos
  #   container_name: rumos
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./rumos/internal/stubs:/app/internal/stubs
  #     - ./rumos/test.db:/app/test.db
  #   networks:
  #     - passcom
  #   command: ["./api"]

  # rumos_ui:
  #   build:
  #     context: ./rumos/ui
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - passcom
  #   depends_on:
  #     - rumos

networks:
  passcom:
    driver: bridge
    external: true
